version: '2'

services:
   rstudio:
     image: rstudio3
     container_name: rstudio
     volumes: 
       - ./import:/home/rstudio/import
     ports:
       - "80:8787"
     environment:
       USER: SpongeBob
       ROOT: "TRUE"
       PASSWORD: SquarePants
     restart: always

