version: '2'

services:
   rstudio:
     image: johanneselias/rstudio-java:1.0
     container_name: rstudio
     volumes: 
       - ./import:/home/rstudio/import
     ports:
       - "8787:8787"
     environment:
       USER: SpongeBob
       ROOT: "TRUE"
       PASSWORD: SquarePants
     restart: always

